name: Practical2 CI

on:
  push:
    paths:
      - "practical2/**"
  pull_request:
    paths:
      - "practical2/**"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [19.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
        working-directory: practical2/books-api-db
      - run: npm run build --if-present
        working-directory: practical2/books-api-db
      - run: npm test
        working-directory: practical2/books-api-db
